services:
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    container_name: nestJS
    ports:
      - '5000:5000'
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:15
    container_name: database
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
