services:
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    container_name: nestJS
    ports:
      - '5000:5000'
    env_file:
      - .env.development.local
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env.development.local
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
