// database
export const ENV_POSTGRES_HOST_KEY = 'POSTGRES_HOST';
export const ENV_POSTGRES_PORT_KEY = 'POSTGRES_PORT';
export const ENV_POSTGRES_USERNAME_KEY = 'POSTGRES_USERNAME';
export const ENV_POSTGRES_PASSWORD_KEY = 'POSTGRES_PASSWORD';
export const ENV_POSTGRES_DATABASE_KEY = 'POSTGRES_DATABASE';
