DROP TABLE IF EXISTS "member" CASCADE;
DROP TABLE IF EXISTS "article" CASCADE;
DROP TABLE IF EXISTS "comment" CASCADE;
DROP TABLE IF EXISTS "stack" CASCADE;
DROP TABLE IF EXISTS "position" CASCADE;
DROP TABLE IF EXISTS "like" CASCADE;
DROP TABLE IF EXISTS "join" CASCADE;
DROP TABLE IF EXISTS "member_stack" CASCADE;
DROP TABLE IF EXISTS "member_position" CASCADE;
DROP TABLE IF EXISTS "article_stack" CASCADE;
DROP TABLE IF EXISTS "article_position" CASCADE;
DROP TYPE IF EXISTS "role";
DROP TYPE IF EXISTS "status";
DROP TYPE IF EXISTS "recruitment_type";
DROP TYPE IF EXISTS "progress_mode";
DROP TYPE IF EXISTS "join_status";

CREATE TYPE "role" AS ENUM (
  'member',
  'admin'
);
CREATE TYPE "status" AS ENUM (
  'active',
  'readonly',
  'blind'
);
CREATE TYPE "recruitment_type" AS ENUM (
  'study',
  'project'
);
CREATE TYPE "progress_mode" AS ENUM (
  'online',
  'offline'
);
CREATE TYPE "join_status" AS ENUM (
  'apply',
  'accept',
  'reject'
);

CREATE TABLE "member" (
  "member_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(100) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "nickname" varchar(100) NOT NULL,
  "role" role NOT NULL DEFAULT 'member',
  "status" status NOT NULL DEFAULT 'active',
  "member_image" varchar(500),
  "introduction" varchar(500),
  "is_deleted" boolean DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "modified_at" timestamp NOT NULL DEFAULT (now())
);
CREATE TABLE "article" (
  "article_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" bigint NOT NULL,
  "title" varchar(255) NOT NULL,
  "content" varchar(1000) NOT NULL,
  "recruitment_type" recruitment_type NOT NULL,
  "recruitment_limit" int NOT NULL,
  "progress_mode" progress_mode NOT NULL,
  "duration" int NOT NULL,
  "closing_date" DATE NOT NULL,
  "view_count" int NOT NULL DEFAULT 0,
  "like_count" int NOT NULL DEFAULT 0,
  "is_closed" BOOLEAN NOT NULL DEFAULT false,
  "is_deleted" boolean DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "modified_at" timestamp NOT NULL DEFAULT (now())
);
CREATE TABLE "comment" (
  "comment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parent_comment_id" bigint,
  "article_id" bigint NOT NULL,
  "member_id" bigint NOT NULL,
  "content" varchar(500) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "modified_at" timestamp NOT NULL DEFAULT (now())
);
CREATE TABLE "stack" (
  "stack_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);
CREATE TABLE "position" (
  "position_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);
CREATE TABLE "like" (
  "like_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" bigint NOT NULL,
  "article_id" bigint NOT NULL
);
CREATE TABLE "join" (
  "join_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "article_id" bigint NOT NULL,
  "member_id" bigint NOT NULL,
  "status" join_status NOT NULL DEFAULT 'apply',
  "created_at" timestamp NOT NULL DEFAULT (now())
);
CREATE TABLE "member_stack" (
  "member_stack_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" int,
  "stack_id" int
);
CREATE TABLE "member_position" (
  "member_stack_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" int,
  "position_id" int
);
CREATE TABLE "article_stack" (
  "article_stack_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "article_id" int,
  "stack_id" int
);
CREATE TABLE "article_position" (
  "article_position_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "article_id" int,
  "position_id" int
);

ALTER TABLE "article" ADD FOREIGN KEY ("member_id") REFERENCES "member" ("member_id");
ALTER TABLE "comment" ADD FOREIGN KEY ("parent_comment_id") REFERENCES "comment" ("comment_id");
ALTER TABLE "comment" ADD FOREIGN KEY ("article_id") REFERENCES "article" ("article_id");
ALTER TABLE "comment" ADD FOREIGN KEY ("member_id") REFERENCES "member" ("member_id");
ALTER TABLE "like" ADD FOREIGN KEY ("member_id") REFERENCES "member" ("member_id");
ALTER TABLE "like" ADD FOREIGN KEY ("article_id") REFERENCES "article" ("article_id");
ALTER TABLE "join" ADD FOREIGN KEY ("member_id") REFERENCES "member" ("member_id");
ALTER TABLE "join" ADD FOREIGN KEY ("article_id") REFERENCES "article" ("article_id");
ALTER TABLE "member_stack" ADD FOREIGN KEY ("member_id") REFERENCES "member" ("member_id");
ALTER TABLE "member_stack" ADD FOREIGN KEY ("stack_id") REFERENCES "stack" ("stack_id");
ALTER TABLE "member_position" ADD FOREIGN KEY ("member_id") REFERENCES "member" ("member_id");
ALTER TABLE "member_position" ADD FOREIGN KEY ("position_id") REFERENCES "position" ("position_id");
ALTER TABLE "article_stack" ADD FOREIGN KEY ("article_id") REFERENCES "article" ("article_id");
ALTER TABLE "article_stack" ADD FOREIGN KEY ("stack_id") REFERENCES "stack" ("stack_id");
ALTER TABLE "article_position" ADD FOREIGN KEY ("article_id") REFERENCES "article" ("article_id");
ALTER TABLE "article_position" ADD FOREIGN KEY ("position_id") REFERENCES "position" ("position_id");